# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
config.vm.box = "generic/ubuntu2204"
config.vm.box_check_update = false
config.vm.provider "virtualbox" do |vb|
vb.memory = "2048"
end

config.vm.define "jenkins" do |jenkins|
jenkins.vm.network "private_network", ip: "192.168.56.10"
jenkins.vm.network "forwarded_port", guest: 8080, host: 18080
jenkins.vm.provision "shell", inline: <<-SHELL

apt-get clean
sudo su
apt-get update -y

apt-get install openjdk-11-jre -y

curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee \
  /usr/share/keyrings/jenkins-keyring.asc > /dev/null
echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
  https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null

apt-get update -y

apt-get install jenkins -y

apt-get remove docker docker-engine docker.io containerd runc -y

apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

mkdir -m 0755 -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

apt-get update -y

chmod a+r /etc/apt/keyrings/docker.gpg

apt-get update -y

apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

SHELL
end

config.vm.define "docker" do |docker|
docker.vm.box = "generic/ubuntu2204"
docker.vm.network "private_network", ip: "192.168.56.11"
docker.vm.network "forwarded_port", guest: 80, host: 18081
docker.vm.provision "shell", inline: <<-SHELL

apt-get clean
apt update -y

apt-get remove docker docker-engine docker.io containerd runc -y
apt-get update -y
apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

mkdir -m 0755 -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

apt-get update -y
chmod a+r /etc/apt/keyrings/docker.gpg
apt-get update -y

apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

SHELL
end

config.vm.provision "shell", inline:  <<-SHELL
apt-get clean
apt update -y
SHELL
end
